### ISSUE TITLE
oauth2client==4.0.0 incompatible

### ISSUE THREAD

**Issue by katsar0v** [googleads/googleads-python-lib#182]
The library does not work with the v4.0.0 of oauth2client, which really bad, because all other Google python libraries use the oauth2client v4.0.0. 
I get:

`AttributeError("'ServiceAccountCredentials' object has no attribute 'CreateHttpHeader'",)
`

**Comment by msaniscalchi** [comment]
Hello,

I will be closing this because it is a duplicate of a [previously reported issue](https://github.com/googleads/googleads-python-lib/issues/110).

Regards,
Mark
