### ISSUE TITLE
AttributeError: 'DocumentCache' object has no attribute 'add'

### ISSUE THREAD

**Issue by estevopaz** [googleads/googleads-python-lib#276]
After update to v201802, from googleads version 9.0.0 to 11.0.1, I get error:
AttributeError: 'DocumentCache' object has no attribute 'add'

Traceback (most recent call last):
  File "/home/estevo/projects/HootInteractive/backend/hoot/adwords/awql.py", line 55, in awql
    .GetReportDownloader(version=hoot.adwords.API_VERSION))
  File "/home/estevo/.local/lib/python3.6/site-packages/googleads/adwords.py", line 413, in GetReportDownloader
    return ReportDownloader(self, version, server)
  File "/home/estevo/.local/lib/python3.6/site-packages/googleads/adwords.py", line 1239, in __init__
    self.proxy_config, self._namespace, self._adwords_client.cache)
  File "/home/estevo/.local/lib/python3.6/site-packages/googleads/common.py", line 792, in __init__
    data = transport.load(endpoint)
  File "/home/estevo/.local/lib/python3.6/site-packages/zeep/transports.py", line 113, in load
    self.cache.add(url, content)
AttributeError: 'DocumentCache' object has no attribute 'add'

**Comment by grivescorbett** [comment]
Ahh yes, Mark is right in that you need to use a Zeep cache or switch back to suds. The preconditions were in the primary code path but not in the reporting helpers. This will be fixed in the next release.
