### ISSUE TITLE
Issue with zeep/six after upgrading to 11.0.1

### ISSUE THREAD

**Issue by babinos87** [googleads/googleads-python-lib#275]
Hi, we got deprecation message of the API version we were using, so we had to upgrade to >11.0.0. We have installed the 11.0.1 version, but now we are getting an error like:

`
Exception Type: | ImportError
cannot import name python_2_unicode_compatible
/usr/local/lib/python2.7/site-packages/zeep/wsdl/definitions.py in <module>, line 21
/usr/bin/uwsgi-core
2.7.13
`

Traceback:

> .......
from googleads import oauth2
  File "/usr/local/lib/python2.7/site-packages/googleads/__init__.py", line 17, in <module>
    from adwords import AdWordsClient
  File "/usr/local/lib/python2.7/site-packages/googleads/adwords.py", line 31, in <module>
    import googleads.common
  File "/usr/local/lib/python2.7/site-packages/googleads/common.py", line 44, in <module>
    import zeep
  File "/usr/local/lib/python2.7/site-packages/zeep/__init__.py", line 1, in <module>
    from zeep.client import CachingClient, Client  # noqa
  File "/usr/local/lib/python2.7/site-packages/zeep/client.py", line 5, in <module>
    from zeep.transports import Transport
  File "/usr/local/lib/python2.7/site-packages/zeep/transports.py", line 9, in <module>
    from zeep.wsdl.utils import etree_to_string
  File "/usr/local/lib/python2.7/site-packages/zeep/wsdl/__init__.py", line 16, in <module>
    from zeep.wsdl.wsdl import Document  # noqa
  File "/usr/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 20, in <module>
    from zeep.wsdl import parse
  File "/usr/local/lib/python2.7/site-packages/zeep/wsdl/parse.py", line 10, in <module>
    from zeep.wsdl import definitions
  File "/usr/local/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 21, in <module>
    from six import python_2_unicode_compatible
ImportError: cannot import name python_2_unicode_compatible

We are using django with uswgi and nginx in a docker container - not sure if this matters, but perhaps, because if I use django shell then this works with no exceptions:

`
from six import python_2_unicode_compatible
`

We don't use a venv so there is no chance that nginx/uwsgi tries to get six from global system (I found this issue in some other six issues on web). 

Those are the installed versions of googleads dependencies:
- googleads==11.0.1
- google-auth [required: >=1.0.0,<2.0.0, installed: 1.4.1]
    - cachetools [required: >=2.0.0, installed: 2.0.1]
    - pyasn1-modules [required: >=0.2.1, installed: 0.2.1]
      - pyasn1 [required: <0.5.0,>=0.4.1, installed: 0.4.2]
    - rsa [required: >=3.1.4, installed: 3.4.2]
      - pyasn1 [required: >=0.1.3, installed: 0.4.2]
    - six [required: >=1.9.0, installed: 1.11.0]
  - google-auth-oauthlib [required: <1.0.0,>=0.0.1, installed: 0.2.0]
    - google-auth [required: Any, installed: 1.4.1]
      - cachetools [required: >=2.0.0, installed: 2.0.1]
      - pyasn1-modules [required: >=0.2.1, installed: 0.2.1]
        - pyasn1 [required: <0.5.0,>=0.4.1, installed: 0.4.2]
      - rsa [required: >=3.1.4, installed: 3.4.2]
        - pyasn1 [required: >=0.1.3, installed: 0.4.2]
      - six [required: >=1.9.0, installed: 1.11.0]
    - requests-oauthlib [required: >=0.7.0, installed: 0.8.0]
      - oauthlib [required: >=0.6.2, installed: 2.0.1]
      - requests [required: >=2.0.0, installed: 2.18.4]
        - certifi [required: >=2017.4.17, installed: 2018.4.16]
        - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
        - idna [required: >=2.5,<2.7, installed: 2.6]
        - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - pytz [required: >=2015.7, installed: 2016.10]
  - PyYAML [required: >=3.11,<4.0, installed: 3.12]
  - requests [required: <3.0.0,>=2.0.0, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2018.4.16]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - suds-jurko [required: <0.7,>=0.6, installed: 0.6]
  - xmltodict [required: <1.0.0,>=0.9.2, installed: 0.11.0]
  - zeep [required: >=2.5.0, installed: 2.5.0]
    - appdirs [required: >=1.4.0, installed: 1.4.3]
    - cached-property [required: >=1.3.0, installed: 1.4.2]
    - defusedxml [required: >=0.4.1, installed: 0.5.0]
    - isodate [required: >=0.5.4, installed: 0.6.0]
      - six [required: Any, installed: 1.11.0]
    - lxml [required: >=3.0.0, installed: 4.2.1]
    - pytz [required: Any, installed: 2016.10]
    - requests [required: >=2.7.0, installed: 2.18.4]
      - certifi [required: >=2017.4.17, installed: 2018.4.16]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.7, installed: 2.6]
      - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
    - requests-toolbelt [required: >=0.7.1, installed: 0.8.0]
      - requests [required: >=2.0.1,<3.0.0, installed: 2.18.4]
        - certifi [required: >=2017.4.17, installed: 2018.4.16]
        - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
        - idna [required: >=2.5,<2.7, installed: 2.6]
        - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
    - six [required: >=1.9.0, installed: 1.11.0]
`

Installed versions of google-api-python-client (not sure if this affects, adding just in case):

- google-api-python-client==1.6.6
  - httplib2 [required: <1dev,>=0.9.2, installed: 0.11.3]
  - oauth2client [required: <5.0.0dev,>=1.5.0, installed: 4.0.0]
    - httplib2 [required: >=0.9.1, installed: 0.11.3]
    - pyasn1 [required: >=0.1.7, installed: 0.4.2]
    - pyasn1-modules [required: >=0.0.5, installed: 0.2.1]
      - pyasn1 [required: <0.5.0,>=0.4.1, installed: 0.4.2]
    - rsa [required: >=3.1.4, installed: 3.4.2]
      - pyasn1 [required: >=0.1.3, installed: 0.4.2]
    - six [required: >=1.6.1, installed: 1.11.0]
  - six [required: <2dev,>=1.6.1, installed: 1.11.0]
  - uritemplate [required: >=3.0.0,<4dev, installed: 3.0.0]

Not sure if this is an issue with googleads module, but raising in case it is.

Thanks,
Babis

**Comment by grivescorbett** [comment]
Hi, thanks for writing in! Hmm... this is a mystery. May I ask which version of Django you're using? I'm not able to easily replicate this problem on my machine. Or if you could put together a simple docker container that shows the issue that would be even better.

In order to unblock you, you can simply change the `soap_impl` field in your googleads.yaml file to the string `suds`. That will use the old framework. We should get this fixed though because suds will be removed in the future.

**Comment by msaniscalchi** [comment]
Hello Babis,

It looks like `python_2_unicode_compatible` was added in six's 1.9.0 release. If you have a version of six installed that is earlier than that, the import error would make sense. You can find where it's defined [here](https://github.com/benjaminp/six/blob/master/six.py#L910).

Of course, you mentioned that you have six 1.11.0 installed, where that wouldn't be an issue. The next thing I would check is whether the Python path being used when you run your app is actually using the version you found installed.

Regards,
Mark

**Comment by babinos87** [comment]
@grivescorbett @msaniscalchi thanks for your replies! Interesting, it seems it is indeed some path issue. I checked the python path as @msaniscalchi suggested, this is the python path at runtime:

`
['.',
 '',
 '/usr/lib/python27.zip',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
...
]
`

The error is thrown from zeep module which is located on /usr/local/lib/python2.7/site-packages/ (six module with version 1.11.0 is installed there as well, so I expected that this would be used).

BUT when I checked each path individually, I have found another version of six installed under /usr/lib/python2.7/dist-packages - which comes BEFORE /usr/local/lib/python2.7/site-packages/ on python path, so THAT version is used. And guess what, six's version it tries to use is 1.8.0!!

Jeez I went crazy with this one... So it seems some issue with the docker container configuration/how packages are installed in the image and not with the googleads module itself. 

Closing.

**Comment by grivescorbett** [comment]
FYI, looks like you may have two different python installations in your docker container :)
